### ISSUE TITLE
Clear terminal in IntelliJ IDEA not working

### ISSUE THREAD

**Issue by mamadaliev** [perfectstorms/life4j#4]
This code does not work in IntelliJ IDEA terminal.
```java
System.out.print("\033[2J\033[H");
```

**Comment by Hardelele** [comment]
To clear data you only need to work on ANSI terminals.

**Comment by mamadaliev** [comment]
> To clear data you only need to work on ANSI terminals.
@Hardelele, you right. Thanks!
